import { theme, type } from "@/theme";
import { StyleSheet } from "react-native";

export const screenStyles = StyleSheet.create({
    title: type.pageTitle,
    screenDescription: type.subtitle,
    sectionTitle: {
        ...type.sectionLabel,
        marginTop: theme.space.lg,
        marginBottom: theme.space.sm,
    },
    summaryCard: {
        backgroundColor: theme.color.surface,
        padding: theme.space.lg,
        borderRadius: theme.radius.lg,
        marginBottom: theme.space.lg,
    },
    leftover: {
        fontSize: 18,
        fontWeight: theme.font.weight.bold,
        marginTop: theme.space.sm,
        color: theme.color.ink,
    },
    content: {
        paddingBottom: 32,
    },
    section: {
        flex: 1,
        padding: theme.space.screenX,
        paddingTop: theme.space.screenTop,
        backgroundColor: theme.color.canvas,
    },
    expenseTextInput: {
        backgroundColor: theme.color.surface,
        borderWidth: 1,
        borderColor: theme.color.border,
        padding: theme.space.md,
        borderRadius: theme.radius.md,
        marginBottom: theme.space.md,
        color: theme.color.ink,
        fontSize: 16,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    loading: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: theme.color.canvas,
    },
    loadingText: {
        ...type.subtitle,
        fontSize: theme.font.page,
        marginTop: 0,
    },
    listHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: theme.space.sm,
        marginBottom: theme.space.md,
    },
    listTitle: type.cardTitle,
    countBadge: {
        minWidth: 24,
        height: 24,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.color.track,
        borderRadius: 12,
        paddingHorizontal: 7,
        marginLeft: theme.space.sm,
    },
    countBadgeText: {
        color: theme.color.muted,
        fontSize: theme.font.kicker,
        fontWeight: theme.font.weight.semibold,
    },
    emptyState: {
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.color.surface,
        borderWidth: 1,
        borderColor: theme.color.border,
        borderRadius: theme.radius.lg,
        paddingHorizontal: theme.space.xxl,
        paddingVertical: 40,
        marginTop: theme.space.md,
    },
    emptyStateIcon: {
        width: 48,
        height: 48,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.color.accentSoft,
        borderRadius: 24,
        marginBottom: 14,
    },
    emptyStateIconText: {
        color: theme.color.accent,
        fontSize: 22,
        fontWeight: theme.font.weight.bold,
    },
    emptyStateTitle: type.cardTitle,
    emptyStateText: {
        maxWidth: 280,
        color: theme.color.muted,
        fontSize: theme.font.body,
        lineHeight: 20,
        textAlign: "center",
        marginBottom: 18,
    },
    leftoverSection: {
        backgroundColor: theme.color.surfaceMuted,
        borderRadius: theme.radius.md,
        padding: theme.space.lg,
        marginTop: theme.space.lg,
        marginBottom: theme.space.xl,
    },
    leftoverLabel: {
        color: theme.color.muted,
        fontSize: theme.font.caption,
        fontWeight: theme.font.weight.regular,
        marginBottom: theme.space.xs,
    },
    leftoverMessage: {
        color: theme.color.muted,
        fontSize: theme.font.kicker,
        lineHeight: 18,
        marginTop: theme.space.xs,
    },
    summaryDetails: {
        borderWidth: 1,
        borderColor: theme.color.border,
        borderRadius: theme.radius.md,
        overflow: "hidden",
        backgroundColor: theme.color.surface,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 14,
        paddingVertical: 13,
    },
    summaryLabel: {
        color: theme.color.muted,
        fontSize: theme.font.body,
    },
    summaryValue: {
        color: theme.color.ink,
        fontSize: theme.font.body,
        fontWeight: theme.font.weight.semibold,
    },
    incomeSummaryAmount: {
        color: theme.color.successText,
        fontSize: theme.font.body,
        fontWeight: theme.font.weight.semibold,
    },
    expenseSummaryAmount: {
        color: theme.color.warning,
        fontSize: theme.font.body,
        fontWeight: theme.font.weight.semibold,
    },
    savingsSummaryAmount: {
        color: theme.color.accent,
        fontSize: theme.font.body,
        fontWeight: theme.font.weight.semibold,
    },
    summaryDivider: {
        height: 1,
        backgroundColor: theme.color.border,
        marginHorizontal: 14,
    },
    resetButtonText: {
        color: theme.color.danger,
        fontSize: theme.font.body,
        fontWeight: theme.font.weight.regular,
        textAlign: "center",
    },
    resetButtonPressed: {
        opacity: 0.65,
    },
});
